### ISSUE TITLE
Add a Cause property

### ISSUE THREAD

**Issue by ansel1** [ansel1/merry#13]
Add a new native merry error property: "cause".  This would be another error.  Useful when a library emits errors of fixed types, and wants to wrap errors from lower level libraries in its own error types without losing information.

Details() would be enhanced to print the stack of causes, perhaps labelling the innermost cause the "root cause".

Cause(err) would get the next error down the cause stack.  RootCause(err) would get the deepest cause.

Could also consider enhancing Is(), or adding an alternate form, for comparing against any of the causes in the stack.

**Comment by drrzmr** [comment]
Great!
This feature will be useful for me!

**Comment by ansel1** [comment]
Fixed in 1.2.0
