### ISSUE TITLE
merry.Details() does not print attached values

### ISSUE THREAD

**Issue by theiostream** [ansel1/merry#17]
Calling `merry.Details(err)` does not print an error's attached values, i.e. `merry.New("x").WithValue("lololol", "asdasdasd")`.

Could it be made to print it? If it is just a matter of implementation, I would be happy to submit a pull request.

**Comment by ansel1** [comment]
Sure, I'd accept a pull request for that.  There's already a method which collects all the attached values as a map, you can probably leverage that.

**Comment by ansel1** [comment]
I've added a RegisterDetail() function in 1.3 to try and address this.
