### ISSUE TITLE
gRPC codes

### ISSUE THREAD

**Issue by zhouzhuojie** [ansel1/merry#20]
Thanks for the awesome go package! Do you have plans to support gRPC codes? This is an extension to the HTTP codes.

Ref: https://godoc.org/google.golang.org/grpc/codes

**Comment by ansel1** [comment]
I haven't considered it, as we haven't adopted grpc yet.  Did you have thoughts on how an extension would look?  Were you thinking of WithGRPCCode()/GRPCCode() functions?  Would it be appropriate for HTTPCode and GRPCCode functions to interact, using each other for defaults it one or the other isn't set?

**Comment by zhouzhuojie** [comment]
Maybe it doesn't have to do anything with HTTP codes. For example

```
import "google.golang.org/grpc/codes"

merry.New("merry error").WithGRPCCode(codes.NotFound)
```

And internally, it just adds a new errorProperty "grpcCode" to the values, in parallel with httpCode.

**Comment by ansel1** [comment]
I looked into this a bit.  I don't really want to import grpc into merry.  It's a dependency which most projects don't need.  I could do WithGRPCCode(uint32) to avoid the import, but I think that would greatly diminish its value.

Also, it looks like it would be useful for errors to implement `GRPCStatus() *Status`, but again, that can't be implemented without importing grpc.

This could be implemented in its own package, but then, it wouldn't be much effort for you to implement these convenience methods in your own project.  merry's `Value()` and `WithValue()` functions are intended to be used to implement your own custom error attributes as needed.

**Comment by zhouzhuojie** [comment]
Thanks, make sense
