### ISSUE TITLE
merry v1.6.0 fails go get

### ISSUE THREAD

**Issue by nvx** [ansel1/merry#24]
```
$ go get github.com/ansel1/merry
go get: github.com/ansel1/merry@v1.5.1 updating to
        github.com/ansel1/merry@v1.6.0 requires
        github.com/ansel1/merry/v2@v2.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

I also note that there is no v2 release tag yet (only beta). I'm guessing making a v2.0.0 release tag and updating the v1 go.mod to point to that release tag would fix it.

I'm not sure if replace tags work as expected when a module is being imported as a library.

**Comment by ansel1** [comment]
Sorry...I'm trying to do v2 as a subfolder in the same branch, but it's a learning process.  Try `go get -u github.com/ansel1/merry@v1.6.1`.  v1's go.mod now explicitly references one of v2's beta tags.  That seemed to fix it for me.

**Comment by nvx** [comment]
yup that seemed to do the trick, cheers!
