### ISSUE TITLE
merry.Errorf returns a stdlib error in some cases which breaks %+v

### ISSUE THREAD

**Issue by mnozhchev** [ansel1/merry#26]
Actual: `fmt.Printf("%+v", merry.Errorf("%w", merry.New("boom")))` does not print a stacktrace 
Expected: It should print a stacktrace. Maybe the stacktrace of the wrapped error.

This example reproduces the issue - https://go.dev/play/p/15d5C3TAbDh .

As far as I understand the code, `merry.Wrap` called by `merry.Errorf` does not wrap the argument if it finds an existing stack trace in its wrap chain. Since `merry.New("boom")` is in the chain, `merry.Errorf` just returns the result of `fmt.Errorf` . However, in that case, `fmt.Printf("%+v")` will not use the Formatter interface implementation in merry.

Workaround: add any value. `merry.Errorf("%w", merry.New("boom"), merry.WithValue("foo", "bar"))` works fine.

**Comment by mnozhchev** [comment]
Loving the library overall! Will be happy to contribute a PR if we discuss where the fix should be. Maybe in WrapSkipping .

**Comment by ansel1** [comment]
Good catch.  Fixed in [911a58f](https://github.com/ansel1/merry/commit/911a58f6dbca8a0ace8dac5c8e5ff52c622fc670)

**Comment by mnozhchev** [comment]
Thank you so much for fixing that so quickly!
