### ISSUE TITLE
Should Location() return empty string?

### ISSUE THREAD

**Issue by Knorkebrot** [ansel1/merry#3]
Hi,

I feel like Location() should return an empty string if it's unknown where the error happened.

* It's the null value of strings
* A file with that name could actually exist (although unlikely)
* Naming a file "" is probably impossible everywhere
* Other functions like Stacktrace() return an empty string as well, not "no stacktrace" :)

What do you think?

**Comment by ansel1** [comment]
Yeah, probably.  I was going for something that would look good in log messages, but it's probably the wrong place for it.  I'll remove it.

**Comment by ansel1** [comment]
Fixed in a66651de935649e9352fc9da4ebade1942cd367b

**Comment by Knorkebrot** [comment]
Thanks :)
