### ISSUE TITLE
Support callbacks to add context to a merry error when it is first captured

### ISSUE THREAD

**Issue by ansel1** [ansel1/merry#8]
When a merry error is first created, or first wrapped around an existing error, it would be cool to optionally invoke configurable a callback.  This would allow users of merry to:
1. capture a different kind of stacktrace (e.g. sentry stacktraces)
2. attach other context information to the error.
3. send the error to a log or error capture system

Callbacks would be registered globally.  They would be invoked whenever a new merry error is created, or when an `error` was wrapped with a merry error.  They would be passed the current merry error, and a stackframe offset from where the merry error is being created, and would return a merry error.

**Comment by keeyim** [comment]
This would be great; I could use it in what I'm working on right now.

**Comment by ansel1** [comment]
Could you tell me a bit about your use case?  What you would do in the callback?

**Comment by keeyim** [comment]
We actually just want to disable the stacktrace for performance reasons.

Ideally we'd like to optionally have the stacktrace on a per error basis, but that's a little different than what you're talking about here.

I actually wrote some code for this over the weekend that addresses the first two items of this issue. I was thinking of uploading it as a pull request, to see if how I did it is close to what you had in mind.

**Comment by ansel1** [comment]
That would be great, I'll take a look.

**Comment by ansel1** [comment]
It looks good, but the more I look at it, the more I think I'm conflating stacktrace capturing with capturing other context...

In your pull request, almost the only realistic use case for registering a callback is to register nil...any other use would *have* to return a []uint...it's unlikely a []uint return from a "capture stacktrace" function is ever going to be anything other than what the default function does.

Plus, you need to add those extra checks into print.go because you don't know how to interpret the value.  Seems like a better way to avoid misinterpretation is to ensure that the value of the `stack` key can *only* be one of two things: 1. nil, or 2. a merry stack.  If an app wants to capture some other type of stack, better to put that value under a different key.

I'm thinking for your use case, it would be better to just introduce a simple, global flag which turns stacktrace capturing on and off.

As a future enhancement, I could add a callback as well, but it would be orthogonal:  its purpose would be to add additional, app-specific context to the error.  It would take an already constructed merry error, plus the offset (if the callback did want to do any additional stack capturing), and return a merry error.  It would not have access to the internal `stack` key, so whatever additional context it captured wouldn't conflict with merry's context.

I could also see adding a functions like merry.WithStack() and merry.WithoutStack(), which would allow one-off stack capturing.  But I'd probably punt on that until someone asked for it.

I'll see if I can do an alternate pull request this evening along these lines, and get your feedback.

**Comment by keeyim** [comment]
I agree that it would probably be better to capture alternate stacktraces as a separate variable in merryError, to avoid the checks I had to add in print.go.

**Comment by ansel1** [comment]
Still waiting on a compelling use case.  There isn't much a callback could do that would be useful.  It doesn't really have any context it can use to do interesting things (i.e. there are no thread locals in go, and no context.Context in scope).  The few things that have come up are logging, metrics, error reporting systems, like sentry.io, and possibly accessing some global state to augment the error.  But haven't gotten any real requests for these.  Closing for now.
